name: Nik

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Clone Nikgapps stuffs
        run: |
          git clone https://github.com/iam-pro/nik-build.git --depth=1 build
          git clone https://github.com/iam-pro/config.git --depth=1

      - name: Setup Build Environment
        working-directory: build
        run: |
          sudo apt update
          sudo apt -y install aapt
          sudo python3 -m pip install wheel setuptools testresources
          sudo pip3 install -r requirements.txt

      - name: Build NikGapps
        working-directory: build
        run: |
          python3 config_control.py 12.1
          ls "/home/runner/work/nikgapps/nikgapps/Releases/12.1/" -sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: "NikGapps-error-arm64-12.1-20220716.zip"
          path: /home/runner/work/nikgapps/nikgapps/Releases/12.1/NikGapps-error-arm64-12.1-20220716.zip
